version: '3.8'

services:
  stock-manager-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-manager-ui
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
